### ISSUE TITLE
Dependencies: Bump Terraform to 1.1.x

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/docker-hashicorp-tools#6]
Proceed with cautious:

- Open a PR to update the update manifest (Bump the regexp)
- Check the updatecli PR that should bump terraform to the latest 1.1.x version
- Then proceed carefully on  jenkins-infra/aws and jenkins-infra/datadog, as their terraform project needs to be checked and updated

**Comment by lemeurherve** [comment]
Solved by https://github.com/jenkins-infra/docker-hashicorp-tools/pull/56
